import { Button, VerticalBox, HorizontalBox, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback record();
    callback stop();
    callback pause();

    in-out property <float> pitch: 0.15;
    in-out property <float> yaw: 0.5;
    in-out property <int> dummy_property: 0; // Dummy property to force updates
    in-out property <[float]> test: [0.5, 0.2, -0.3, -0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]; // Dummy data for testing

    pure callback render_plot(/* width */ int, /* height */ int, /* pitch */ float, /* yaw */ float, /* amplitude */ float, /* dummy_property */ int) -> image;

    VerticalBox {
        HorizontalBox {
            Button {
                text: "⏺"; // Unicode für "Record"
                clicked => { root.record(); }
            }
            Button {
                text: "⏹"; // Unicode für "Stop"
                clicked => { root.stop(); }
            }
            Button {
                text: "⏸"; // Unicode für "Pause"
                clicked => { root.pause(); }
            }
        }

        Rectangle {
            height: 200px;
            width: 1000px;
            for item[idx] in root.test: Rectangle {
                width: 1px;
                padding: 0px;
                border-width: 0px;
                height: item * parent.height / 2;
                y: (parent.height / 2) - (Math.mod(idx, 2) - 1) * item * (parent.height / 2);
                x: idx / 2 * 1px;
                background: blue;
            }
        }
        
        HorizontalBox {
            Text {
                text: "Amplitude:";
                font-weight: 600;
                vertical-alignment: center;
            }

            amplitude-slider := Slider {
                minimum: 0;
                maximum: 100;
                value: 50;
            }
        }
    }
}
