import { Button, VerticalBox, HorizontalBox, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback record();
    callback stop();
    callback pause();

    in-out property <int> wav1start: 0;
    in-out property <[{l: float, r: float}]> wav1; // Extended dummy data for testing

    min-width: 1010px;

    VerticalBox {
        HorizontalBox {
            Button {
                text: "⏺"; // Unicode für "Record"
                clicked => { root.record(); }
            }
            Button {
                text: "⏹"; // Unicode für "Stop"
                clicked => { root.stop(); }
            }
            Button {
                text: "⏸"; // Unicode für "Pause"
                clicked => { root.pause(); }
            }
        }

        Rectangle {
            height: 200px;
            width: 1000px;
            for item[idx] in root.wav1: Rectangle {
                width: 1px;
                padding: 0px;
                border-width: 0px;
                height: item.l * parent.height / 4;
                y: parent.height / 4 - item.l * (parent.height / 8);
                x: (idx - wav1start) * 1px;
                background: blue;
            }
            for item[idx] in root.wav1: Rectangle {
                width: 1px;
                padding: 0px;
                border-width: 0px;
                height: item.r * parent.height / 4;
                y: parent.height / 4 * 3 - item.r * (parent.height / 8);
                x: (idx - wav1start) * 1px;
                background: blue;
            }
        }
        
        HorizontalBox {
        }
    }
}
